SELECT LOWER('hI tHeRe');
SELECT LOWER('HI THERE');
SELECT LOWER('TOM');

SELECT LPAD('7235', 8, '20');

SELECT LTRIM('00123', '001');

SELECT MD5('ABC')

SELECT POSITION('Tutorial' IN 'GeeksForGeeks Tutorial');
SELECT POSITION('B' in 'A B C')
SELECT POSITION('ak' IN 'Idrak')
